### ISSUE TITLE
Rapps feature/issue prioritisation

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_app_platform#232]
@bit-pirate, @jihoonl 

Since we're now collecting a fair bit of information on this, I thought I'd keep track of things here.
- **Rapp Definitions**
  - [x] relative paths to rapp internal files (interactions, public_interface): https://github.com/robotics-in-concert/rocon_app_platform/issues/231
  - [x] add type information to public interfaces, (needs an issue) #244 
  - [x] add specification for public parameters, #170 
- **Rapp Manager Implementations**
  - [x] implement parameters by exposing roslaunch args, #170 
  - [x] expose rapp implementation information: #226
  - [x] preferred, not highlander policy for execution of rapps, allow multiple rapp implementations with the same parent, #187, #230
- **Other**
  - [x] redefine teleop rapp: https://github.com/robotics-in-concert/rocon_app_platform/issues/224

**Comment by bit-pirate** [comment]
None of the issues linked above are urgent (IMO) and hence can be postponed to after the demo

**Comment by stonier** [comment]
Ok. Update here if you come across any _showstoppers_ and I'll tackle them.

**Comment by jihoonl** [comment]
Bug label?

**Comment by bit-pirate** [comment]
> Bug label?

Removed. The above issues are either results of design decisions or enhancements.

**Comment by jihoonl** [comment]
For the record, 

All the rapp attributes except parent_name will get relative path after resolving #231, we have decided not to use <package>/<filename> based resource finder.

**Comment by jihoonl** [comment]
All done!
