### ISSUE TITLE
App manager and capability server integration

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_app_platform#66]
Following up on https://github.com/osrf/capabilities/issues/2.

**TODO**
- [x] implement pruning of available apps based on available capabilities
- [x] implement starting and stopping apps
- [x] implement remapping according to the capability interfaces
- [ ] sync manual, concert and capability remappings
- [ ] more to come

**Comment by bit-pirate** [comment]
regarding _sync manual, concert and capability remappings_: https://github.com/robotics-in-concert/rocon_app_platform/issues/98

**Comment by stonier** [comment]
Closing this...follow up regarding concert handles is in #98.
